version: '3'
services:
  server:
    image: node:latest
    depends_on:
      - mysql1
    container_name: coden_associates_sight
    ports:
      - "8080:8080"

  mysql1:
    image: mysql:5.7
    platform: linux/amd64
    restart: always
    container_name: db1
    environment:
      - MYSQL_DATABASE=test_db
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - '3306:3306'
    stdin_open: true
    tty: true