version: '3'
services:
  server:
    build:
       context: ./server
       dockerfile: ./Dockerfile
    depends_on:
      - mongodb
    container_name: coden_associates_ecom
    ports:
      - "8000:8000"
    volumes:
      - "./server:/app/src"

    command: "npx nodemon src/server.js"

  mongodb:
    image: mongo:latest
    container_name: Db_ecom
    ports:
      - "3306:3306"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
